export const destinations = [
  {
    slug: "united-kingdom",
    name: { en: "United Kingdom", sw: "Uingereza" },
    countryCode: "gb",
    flag: "🇬🇧",
    hero: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "Clear one-year master's routes and a large Tanzanian alumni community in London, Manchester, and Birmingham.",
      sw: "Njia wazi za uzamili wa mwaka mmoja na jamii kubwa ya Watanzania London, Manchester, na Birmingham.",
    },
    fields: ["Business", "Public health", "Law", "Engineering"],
    budget: { usd: "18,000–32,000", tzs: "TZS 47–84m" },
    why: {
      en: "Familiar academic English, September and January intakes, and a Graduate Route families can plan around (length changes for applications from 2027).",
      sw: "Kiingereza cha kitaaluma kinachojulikana, ulaji wa Septemba na Januari, na Graduate Route familia zinazoweza kupanga (urefu unabadilika kwa maombi kuanzia 2027).",
    },
  },
  {
    slug: "united-states",
    name: { en: "United States", sw: "Marekani" },
    countryCode: "us",
    flag: "🇺🇸",
    hero: "https://images.unsplash.com/photo-1485738422979-f5c2755b1d76?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "Flexible majors and strong STEM labs — best when you have time for SAT/English and a longer visa file.",
      sw: "Fani zinazobadilika na maabara imara za STEM — bora unapokuwa na muda wa SAT/Kiingereza na faili refu la viza.",
    },
    fields: ["Computer science", "Business", "Health sciences"],
    budget: { usd: "22,000–45,000", tzs: "TZS 58–118m" },
    why: {
      en: "Campus life is broad. We only shortlist schools that still issue I-20s to East African applicants this cycle.",
      sw: "Maisha ya chuo ni mapana. Tunachagua vyuo vinavyotoa I-20 kwa waombaji wa Afrika Mashariki.",
    },
  },
  {
    slug: "canada",
    name: { en: "Canada", sw: "Kanada" },
    countryCode: "ca",
    flag: "🇨🇦",
    hero: "https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "Colleges and universities with co-op terms — popular with families who want a work-linked study path.",
      sw: "Vyuo vya kozi na vyuo vikuu vyenye co-op — vinapendwa na familia zinazotaka njia ya kazi.",
    },
    fields: ["IT", "Nursing pathways", "Business", "Trades"],
    budget: { usd: "16,000–28,000", tzs: "TZS 42–74m" },
    why: {
      en: "We track provincial attestation (PAL/TAL), intake caps, and PGWP-eligible programmes so you do not apply into a closed window.",
      sw: "Tunafuatilia uthibitisho wa mikoa (PAL/TAL), mipaka ya ulaji, na programu zinazostahili PGWP ili usiombe dirisha lililofungwa.",
    },
  },
  {
    slug: "australia",
    name: { en: "Australia", sw: "Australia" },
    countryCode: "au",
    flag: "🇦🇺",
    hero: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "February and July starts, outdoor campuses, and a straightforward student-visa checklist.",
      sw: "Mwanzo wa Februari na Julai, vyuo vya nje, na orodha wazi ya viza ya wanafunzi.",
    },
    fields: ["Engineering", "Nursing", "Hospitality", "IT"],
    budget: { usd: "18,000–30,000", tzs: "TZS 47–79m" },
    why: {
      en: "A good fit if you want English-medium study with warmer weather than the UK winter.",
      sw: "Inafaa ukitaka masomo kwa Kiingereza na hali ya hewa ya joto kuliko majira ya baridi ya Uingereza.",
    },
  },
  {
    slug: "india",
    name: { en: "India", sw: "India" },
    countryCode: "in",
    flag: "🇮🇳",
    hero: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "The most common first destination from Tanzania for engineering, medicine pathways, and IT — closer and more affordable.",
      sw: "Kituo cha kwanza kinachojulikana kutoka Tanzania kwa uhandisi, njia za tiba, na IT — karibu na nafuu.",
    },
    fields: ["Engineering", "IT", "Pharmacy", "Business"],
    budget: { usd: "3,500–8,000", tzs: "TZS 9–21m" },
    why: {
      en: "Shorter flights from JNIA, familiar food options, and a large East African student presence.",
      sw: "Safari fupi kutoka JNIA, chakula kinachojulikana, na wanafunzi wengi wa Afrika Mashariki.",
    },
  },
  {
    slug: "china",
    name: { en: "China", sw: "China" },
    countryCode: "cn",
    flag: "🇨🇳",
    hero: "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "English-taught engineering and business degrees, plus scholarship tracks at selected partners.",
      sw: "Shahada za uhandisi na biashara kwa Kiingereza, pamoja na njia za ufadhili kwa washirika teule.",
    },
    fields: ["Engineering", "Medicine", "Business", "Mandarin + major"],
    budget: { usd: "3,000–7,500", tzs: "TZS 8–20m" },
    why: {
      en: "We only place into English-medium programmes unless you specifically want a language year.",
      sw: "Tunaweka tu kwenye programu za Kiingereza isipokuwa unataka mwaka wa lugha.",
    },
  },
  {
    slug: "malaysia",
    name: { en: "Malaysia", sw: "Malaysia" },
    countryCode: "my",
    flag: "🇲🇾",
    hero: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "UK-linked degrees in Kuala Lumpur and Cyberjaya at a mid-range cost, with a large Muslim student community.",
      sw: "Shahada zinazounganishwa na Uingereza Kuala Lumpur na Cyberjaya kwa gharama ya kati, na jamii kubwa ya wanafunzi Waislamu.",
    },
    fields: ["Business", "IT", "Hospitality", "Engineering"],
    budget: { usd: "4,500–10,000", tzs: "TZS 12–26m" },
    why: {
      en: "A practical step if the UK is the long-term goal but this year's budget is tighter.",
      sw: "Hatua ya busara ikiwa Uingereza ni lengo la muda mrefu lakini bajeti ya mwaka huu ni ndogo.",
    },
  },
  {
    slug: "germany",
    name: { en: "Germany", sw: "Ujerumani" },
    countryCode: "de",
    flag: "🇩🇪",
    hero: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "Low public tuition if you can meet German or high English bars and plan a blocked account.",
      sw: "Ada ndogo ya umma ukikidhi vigezo vya Kijerumani au Kiingereza na kupanga akaunti iliyozuiliwa.",
    },
    fields: ["Engineering", "Computer science", "Renewable energy"],
    budget: { usd: "Semester fee + ~€11,904 blocked", tzs: "Ada ya muhula + fedha zilizohifadhiwa" },
    why: {
      en: "We are honest about language: some programmes are English, many still need German for daily life. Tanzanian files usually go through uni-assist, not APS.",
      sw: "Tunasema ukweli kuhusu lugha: baadhi ya programu ni Kiingereza, nyingi bado zinahitaji Kijerumani. Faili za Kitanzania mara nyingi hupitia uni-assist, si APS.",
    },
  },
  {
    slug: "new-zealand",
    name: { en: "New Zealand", sw: "New Zealand" },
    countryCode: "nz",
    flag: "🇳🇿",
    hero: "https://images.unsplash.com/photo-1507699622108-4be3abd81d6d?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "Smaller campuses and a calmer pace — a strong fit for environmental and hospitality degrees.",
      sw: "Vyuo vidogo na mwendo tulivu — inafaa kwa shahada za mazingira na ukarimu.",
    },
    fields: ["Environment", "Hospitality", "Agriculture"],
    budget: { usd: "16,000–26,000", tzs: "TZS 42–68m" },
    why: {
      en: "Fewer Tanzanian applicants means we can give each file more counsellor time.",
      sw: "Waombaji wachache wa Kitanzania humaanisha muda zaidi wa mshauri kwa kila faili.",
    },
  },
  {
    slug: "ireland",
    name: { en: "Ireland", sw: "Ireland" },
    countryCode: "ie",
    flag: "🇮🇪",
    hero: "https://images.unsplash.com/photo-1590089415225-401ed6f9db8e?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "English-speaking Europe with growing tech and pharma hiring around Dublin.",
      sw: "Ulaya yenye Kiingereza na ajira zinazokua za teknolojia na dawa karibu na Dublin.",
    },
    fields: ["Tech", "Pharma", "Business"],
    budget: { usd: "14,000–26,000", tzs: "TZS 37–68m" },
    why: {
      en: "A compact alternative to the UK when you want an EU base.",
      sw: "Mbadala mdogo wa Uingereza unapotaka kituo cha EU.",
    },
  },
  {
    slug: "netherlands",
    name: { en: "Netherlands", sw: "Uholanzi" },
    countryCode: "nl",
    flag: "🇳🇱",
    hero: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "Many bachelor's taught in English, with a culture of independent study.",
      sw: "Shahada nyingi zilizofundishwa kwa Kiingereza, na utamaduni wa kujifunza kwa uhuru.",
    },
    fields: ["Design", "Social sciences", "Engineering"],
    budget: { usd: "10,000–20,000", tzs: "TZS 26–53m" },
    why: {
      en: "We prepare you for the numerus-fixus and housing race, which start earlier than families expect.",
      sw: "Tunakuandaa kwa numerus-fixus na mbio za makazi, zinazoanza mapema kuliko familia zinavyotarajia.",
    },
  },
  {
    slug: "france",
    name: { en: "France", sw: "Ufaransa" },
    countryCode: "fr",
    flag: "🇫🇷",
    hero: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "Public tuition stays low; English tracks exist in business and engineering schools.",
      sw: "Ada ya umma inabaki chini; njia za Kiingereza zipo katika shule za biashara na uhandisi.",
    },
    fields: ["Business", "Fashion", "Engineering"],
    budget: { usd: "3,000–15,000", tzs: "TZS 8–40m" },
    why: {
      en: "We only recommend France if you are ready for Campus France steps and at least basic French.",
      sw: "Tunapendekeza Ufaransa tu ikiwa uko tayari kwa hatua za Campus France na Kifaransa cha msingi.",
    },
  },
  {
    slug: "japan",
    name: { en: "Japan", sw: "Japan" },
    countryCode: "jp",
    flag: "🇯🇵",
    hero: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1600&q=80",
    summary: {
      en: "English-medium graduate programmes and a growing set of undergraduate MEXT-linked paths.",
      sw: "Programu za uzamili kwa Kiingereza na njia zinazokua za shahada zinazohusiana na MEXT.",
    },
    fields: ["Robotics", "Design", "Business"],
    budget: { usd: "5,000–12,000", tzs: "TZS 13–32m" },
    why: {
      en: "Timelines are long. We start the year before you want to land.",
      sw: "Ratiba ni ndefu. Tunaanza mwaka kabla unapotaka kufika.",
    },
  },
] as const;

export type DestinationSlug = (typeof destinations)[number]["slug"];
